#!/bin/sh

# run sxhkd with sh
export SXHKD_SHELL='/usr/bin/sh'

# run a few necessary programs
sxhkd &
nitrogen --set-zoom-fill --random &
picom &

if [[ $HOSTNAME == coulter ]]; then
	# tint2 and conky for dual monitor
	tint2 -c $HOME/.config/tint2/midday.tint2rc &
	conky --config=$HOME/.config/conky/midday.conf &
	bspc monitor DP-4 -d 1 2 3 4 5
	bspc monitor DP-5 -d 6 7 8 9 0
else
	# only tint2 for single monitor devices
	tint2 -c $HOME/.config/tint2/lefty.tint2rc &
	bspc monitor -d 1 2 3 4 5 6 7 8 9 0
fi

# bspc config settings
bspc config border_width 2
bspc config window_gap 0
bspc config -m DP-4 right_padding 100

bspc config split_ratio 0.54
bspc config borderless_monocle true
bspc config gapless_monocle true

# Border colors
bspc config normal_border_color "#1d1f21"
bspc config focused_border_color "#bf616a"
bspc config presel_feedback_color "#172b2a"

# Pointer behavior
bspc config pointer_modifier mod1
bspc config focus_follows_pointer true
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Program rules
bspc rule -a Zathura state=tiled
bspc rule -a Onboard state=floating
