#!/bin/sh

# Set some bsp specific stuff
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# bspc config settings
bspc config border_width 2
bspc config window_gap 0

bspc config split_ratio 0.54
bspc config borderless_monocle true
bspc config gapless_monocle true

# Border colors
bspc config normal_border_color "#1d1f21"
bspc config focused_border_color "#bf616a"
bspc config presel_feedback_color "#172b2a"

# Pointer behavior
bspc config pointer_modifier mod1
bspc config focus_follows_pointer true
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Program rules
bspc rule -a Zathura state=tiled
