#!/bin/sh
while read file
do
        case "$1" in
        "s")
                nitrogen --save --set-zoom-fill "$file" &&
                notify-send -i "$file" "Wallpaper changed!" ;;
        esac
done
