-- To make bufferline look good
local color_bar = "#1f2335"
local color_inactive = "#1f2335"
local color_active = "none"

return {
  {
    "akinsho/bufferline.nvim",
    opts = {
      options = {
        show_buffer_close_icons = false,
        separator_style = "slope",
      },
      highlights = {
        fill = { bg = color_bar },
        separator = { bg = color_inactive, fg = color_bar },
        separator_visible = { bg = color_active, fg = color_bar },
        separator_selected = { bg = color_active, fg = color_bar },
        background = { bg = color_inactive },
        buffer_visible = { bg = color_active },
        buffer_selected = { bg = color_active },
        diagnostic = { bg = color_inactive },
        diagnostic_visible = { bg = color_active },
        diagnostic_selected = { bg = color_active },
        hint = { bg = color_inactive },
        hint_visible = { bg = color_active },
        hint_selected = { bg = color_active },
        hint_diagnostic = { bg = color_inactive },
        hint_diagnostic_visible = { bg = color_active },
        hint_diagnostic_selected = { bg = color_active },
        info = { bg = color_inactive },
        info_visible = { bg = color_active },
        info_selected = { bg = color_active },
        info_diagnostic = { bg = color_inactive },
        info_diagnostic_visible = { bg = color_active },
        info_diagnostic_selected = { bg = color_active },
        warning = { bg = color_inactive },
        warning_visible = { bg = color_active },
        warning_selected = { bg = color_active },
        warning_diagnostic = { bg = color_inactive },
        warning_diagnostic_visible = { bg = color_active },
        warning_diagnostic_selected = { bg = color_active },
        error = { bg = color_inactive },
        error_visible = { bg = color_active },
        error_selected = { bg = color_active },
        error_diagnostic = { bg = color_inactive },
        error_diagnostic_visible = { bg = color_active },
        error_diagnostic_selected = { bg = color_active },
        modified = { bg = color_inactive },
        modified_visible = { bg = color_active },
        modified_selected = { bg = color_active },
        duplicate = { bg = color_inactive },
        duplicate_visible = { bg = color_active },
        duplicate_selected = { bg = color_active },
        indicator_visible = { bg = color_active },
        indicator_selected = { bg = color_active },
        pick = { bg = color_inactive },
        pick_visible = { bg = color_active },
        pick_selected = { bg = color_active },
      },
    },
  },
}
